#! /bin/sh

# Filename: /alcove-hooks/66-qbittorrent-nox

NAME="qbittorrent-nox"
COMMAND="/usr/bin/${NAME}"
PIDFILE="/var/run/${NAME}.pid"

start() {
  stop > /dev/null 2>&1
  nohup  ${COMMAND} > /dev/null 2>&1 &
  echo ${!} > ${PIDFILE}
}

stop() {
  kill -s 15 $(cat ${PIDFILE})

  while pgrep ${NAME} > /dev/null 2>&1; do
    kill -s 15 $(cat ${PIDFILE})
    sleep 1
  done

  rm -f ${PIDFILE}
}

case "${1}" in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
