#! /bin/sh

# Filename: /alcove-hooks/00-extsd

# NOTICE: To use this hook, you must be ensure that
#         you have been commented the related path on alcove.binds .

NAME="sshd"
DEVICE="/dev/block/mmcblk1p2"
DIRPATH="/mnt/extsd"

start() {
  stop > /dev/null 2>&1
  mount ${DEVICE} ${DIRPATH}
}

stop() {
  umount ${DIRPATH}
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
