#! /bin/sh

# Filename: /alcove-hooks/00-zram

NAME="zram"
DEVICE="/dev/block/zram0"
CFGDIR="/sys/block/zram0"

start() {
  stop > /dev/null 2>&1
  {
    echo $((1*1024*1024*1024)) > ${CFGDIR}/disksize
    mkswap ${DEVICE}
    swapon ${DEVICE}
  } > /dev/null 2>&1
}

stop() {
  swapoff ${DEVICE}
  echo 1 > ${CFGDIR}/reset
}

case "${1}" in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
