#! /bin/sh

# Filename: /alcove-hooks/00-zram

NAME="zram"
CONFDIR="/sys/block/zram0"
DEVICE="/dev/block/zram0"

start() {
  stop > /dev/null 2>&1
  {
    echo $((1*1024*1024*1024)) > ${CONFDIR}/disksize
    mkswap ${DEVICE}
    swapon ${DEVICE}
  } > /dev/null 2>&1
}

stop() {
  swapoff ${DEVICE}
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
