#! /bin/sh

# Filename: /alcove-hooks/40-weborf

# NOTICE: This hook may not safe(run as root), so please consider carefully.

NAME="weborf"
PIDFILE="/var/run/${NAME}.pid"

start() {
  stop > /dev/null 2>&1
  nohup  weborf -b /mnt -p 80 > /dev/null 2>&1 &
  echo ${!} > ${PIDFILE}
}

stop() {
  kill -s 15 $(cat ${PIDFILE})
  rm -f ${PIDFILE}
}

case "${1}" in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
